[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "microcal"
version = "0.1.0"
description = "Chromatic shift correction for multi-channel fluorescence microscopy"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "scikit-image",
    "tifffile",
    "rich",
]

[dependency-groups]
test = ["pytest", "pytest-cov", "pytest-xdist>=3.8.0"]
dev = [
    "mypy",
    "pre-commit",
    "pytest-cov",
    "pytest",
    "ruff",
]

[project.optional-dependencies]
ndv = ["ndv[pygfx,pyqt]"]
ndv-jup = ["ndv[pygfx,jupyter]", "jupyter-rfb<=0.5.4"]

[tool.hatch.build.targets.wheel]
packages = ["src/microcal"]

# https://docs.astral.sh/ruff/configuration/
[tool.ruff]
line-length = 88
target-version = "py310"
src = ["src", "tests"]
fix = true
unsafe-fixes = true

# https://docs.astral.sh/ruff/rules
[tool.ruff.lint]
pydocstyle = { convention = "numpy" }
select = [
    "E",    # style errors
    "W",    # style warnings
    "F",    # flakes
    "D",    # pydocstyle
    "D417", # Missing argument descriptions in Docstrings
    "I",    # isort
    "UP",   # pyupgrade
    "C4",   # flake8-comprehensions
    "B",    # flake8-bugbear
    "A001", # flake8-builtins
    "ANN",  # flake8-annotations
    "RUF",  # ruff-specific rules
    "TC",   # flake8-type-checking
    "TID",  # flake8-tidy-imports
]
ignore = [
    "ANN401", # allow the use of Any type
    "D401",   # First line should be in imperative mood (remove to opt in)
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["D", "S"]

[tool.ruff.format]
docstring-code-format = true

# https://docs.pytest.org/en/6.2.x/customize.html
[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
filterwarnings = []

# https://mypy.readthedocs.io/en/stable/config_file.html
[tool.mypy]
files = "src/**/"
strict = true
disallow_any_generics = false
disallow_subclassing_any = false
show_error_codes = true
pretty = true
exclude = ".*\\.ipynb$"

# Ignore missing imports for large packages not available in pre-commit
ignore_missing_imports = true

[tool.check-manifest]
ignore = [".pre-commit-config.yaml", ".ruff_cache/**/*", "tests/**/*"]

[tool.typos.default]
extend-ignore-identifiers-re = ["ND=ND", "thr=thr", "iy=iy"]
